# Generated by Django 2.1 on 2019-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000, verbose_name='описание')),
                ('status', models.CharField(choices=[('new', 'новая'), ('in_progress', 'В процессе'), ('Finished', 'Завершена')], default='new', max_length=40, verbose_name='Статус')),
                ('date_perf', models.TextField(blank=True, default=' ', help_text='Use the following format: <em>YYYY-MM-DD</em>.', verbose_name='Время изменения')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
